SCR_MissionHeader {
 m_sName "Wasteland - Novka"
 m_sAuthor "Wasteland Reforged"
 m_sPath "Missions/WastelandReforged_Novka.conf"
 m_sDescription "Wasteland is a PvPvE sandbox gamemode."
 m_sDetails "Wasteland is a PvPvE sandbox gamemode."
 m_sIcon "{DC1BA61142CCA163}Art/workshop-novka.edds"
 m_sLoadingScreen "{9D472902BC0BEFB3}Art/splash-novka.edds"
 m_sPreviewImage "{DC1BA61142CCA163}Art/workshop-novka.edds"
 m_sGameMode "Wasteland"
 m_iPlayerCount 64
}