enum WR_MissionType
{
    EMPTY, // DO NOT USE! This status indicates to a proxy that the mission object it is receiving is a placeholder.
	GEOCACHE,
	ABANDONED_HELICOPTER,
	ABANDONED_SUPPLIES,
	ABANDONED_VEHICLE,
	VEHICLE_WRECK,
	MEDICAL_SUPPLIES,
	WEAPON_CACHE,
	SNIPER_SQUAD,
    CAPTURE_HELICOPTER,
    CAPTURE_VEHICLE,
	CAPTURE_BASE,
	CAPTURE_OUTPOST
}