enum WR_MissionType
{
    EMPTY, // DO NOT USE! This status indicates to a proxy that the mission object it is receiving is a placeholder.
	ABANDONED_HELICOPTER,
	ABANDONED_SUPPLIES,
	ABANDONED_VEHICLE,
	CAPTURE_BASE,
	CAPTURE_HELI_ARMED,
	CAPTURE_HELI_TRANSPORT,
	CAPTURE_OUTPOST,
	CAPTURE_VEHICLE,
	GEOCACHE,
	MEDICAL_SUPPLIES,
	MORTAR,
	SNIPER_SQUAD,
	VEHICLE_WRECK,
	WEAPON_CACHE,
}