SCR_MissionHeader {
 World "{734BF22551AEB544}Worlds/WastelandWorthyIslands.ent"
 SystemsConfig "{3CA3D64CBFD9C166}Missions/WastelandReforged_WorthyIslands.conf"
 m_sName "Battlefield Wasteland - Worthy Islands"
 m_sAuthor "Mohred"
 m_sPath "{734BF22551AEB544}Worlds/WastelandWorthyIslands.ent"
 m_sDescription "PvPvE Wasteland sandbox on Worthy Islands."\
 ""
 m_sDetails "Based on Wasteland Reforged, created by Paul (paul2kandrews) and Choco (echurchill1) of Armageddon Gaming."\
 "https://github.com/Wasteland-Reforged/WastelandReforged"\
 ""\
 "Modified fork maintained for Battlefield Wasteland."\
 "Licensed under the Arma Public License (APL): https://www.bohemia.net/community/licenses/arma-public-license"\
 ""
 m_sIcon "{07B8F6A453998A68}Art/wasteland.edds"
 m_sLoadingScreen "{07B8F6A453998A68}Art/wasteland.edds"
 m_sPreviewImage "{07B8F6A453998A68}Art/wasteland.edds"
 m_iPlayerCount 128
 m_eEditableGameFlags 6
 m_eDefaultGameFlags 6
 m_fNightTimeAcceleration 4
}