SystemSettings : "{45C53F06BA17238D}configs/Systems/SystemsConfig.conf" {
 Systems {
  WR_MissionSystem "{62D4535DAF3772E6}" {
   m_Config WR_MissionSystemConfig "{649A5E1ACEFBED3B}" : "{ACE447A0FF06DEAF}Configs/Missions/WR_MissionSystemConfigNovka.conf" {
   }
  }
 }
}