SCR_CampaignFaction : "{8053DB656DD18B14}Configs/Factions/FIA.conf" {
 UIInfo SCR_FactionUIInfo "{5570936866E0AD08}" {
  Name "Independent"
  m_sNameUpper "INDEPENDENT"
 }
 m_sFactionFlag "{4A69586A3A1F7E6F}Art/Flags/indfor-saturated.edds"
 m_bFriendlyToSelf 0
 m_aEntityCatalogs {
  SCR_EntityCatalogMultiList "{5C68A0EABB80080C}" {
   m_aEntityEntryList {
    SCR_EntityCatalogEntry "{689964A819C9F759}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{689964A819C9F75D}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{689964A819C9F75C}" {
     m_bEnabled 0
    }
   }
  }
 }
 m_sCommanderMenuEntries "{3F001B67628E0EF1}Configs/FactionCommander/CampaignFactionCommanderMenuEntries.conf"
 m_DefaultCharacterPrefab "{CEE7531F4FBAEB38}Prefabs/Characters/Factions/INDFOR/WR_Character_FIA_Base.et"
 m_BaseBuildingHQ "{16E06E20F4641F8A}PrefabsEditable/Auto/Compositions/Slotted/SlotFlatSmall/E_Headquarters_S_Conflict_FIA_01.et"
 m_BaseBuildingSupplyDepot "{E8B6339148792C0E}PrefabsEditable/Auto/Compositions/Slotted/SlotFlatSmall/E_SupplyCache_S_FIA_01.et"
 m_RadioMsgWhitelistConfig SCR_CampaignRadioMsgWhitelistConfig "{65BD330B410EC0D7}" : "{E4DFFC55BD100DCA}Configs/Campaign/CampaignRadioMsgWhitelistConfig.conf" {
 }
}