SystemSettings : "{45C53F06BA17238D}configs/Systems/SystemsConfig.conf" {
 Systems {
  WR_MissionSystem "{62D4535DAF3772E6}" {
   m_Config WR_MissionSystemConfig "{689C3DDB75277ED1}" : "{2163DE0D66C8519F}Configs/Missions/WR_MissionSystemConfigChernarus.conf" {
    m_aPlayercountMissionThresholds {
     0
     0
     5
     25
     40
    }
   }
  }
 }
}