StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{6213697BFBC7A0CF}" {
   Id "AR-WR_Briefing_Intro_1_Desc"
   Target_en_us "Wasteland is a PvP sandbox gamemode."\
   ""\
   "Collect weapons, vehicles, and equipment to use in battle against other players. Gather supplies and build a base to store your loot."\
   ""\
   "With no specific end goal, compete with other players to claim mission rewards and become the dominant force."
   Modified 1645560307
   Author "Paul Andrews"
   LastChanged "Paul Andrews"
  }
  CustomStringTableItem "{6213697A285F9277}" {
   Id "AR-WR_Briefing_Intro_1_Title"
   Target_en_us "What is Wasteland?"
   Modified 1645560366
   Author "Paul Andrews"
   LastChanged "Paul Andrews"
  }
  CustomStringTableItem "{6213697BD3686382}" {
   Id "AR-WR_Briefing_Intro_2_Desc"
   Target_en_us "Wasteland is totally free-form. Players are free to play however they like."\
   ""\
   "Maybe you’ll establish a large fortress with your team as BLUFOR or OPFOR. Or, maybe you’ll go solo and be a thorn in the side of the larger factions as an Independent. Maybe you’ll set up a roadblock to ambush enemy players. Or, maybe you’ll go for every mission you can and hoard the weapons and gear you earn. "\
   ""\
   "It’s all possible in Wasteland. The choice is yours."
   Modified 1645560315
   Author "Paul Andrews"
   LastChanged "Paul Andrews"
  }
  CustomStringTableItem "{6213697BECF4A2B5}" {
   Id "AR-WR_Briefing_Intro_2_Title"
   Target_en_us "What can I do in Wasteland?"
   Modified 1645560370
   Author "Paul Andrews"
   LastChanged "Paul Andrews"
  }
  CustomStringTableItem "{6213697BBFFAA238}" {
   Id "AR-WR_Briefing_Intro_3_Desc"
   Target_en_us "BLUFOR and OPFOR — Team factions. Members are required to work together. Killing or griefing allies is prohibited when playing on either of these factions. The positions of allies are visible on the map at all times."\
   ""\
   "Independent — Free-for-all faction. Players may engage anyone in any faction, including other Independents. All other players’ positions are hidden on the map, unless they are members of the same group."
   Modified 1645560340
   Author "Paul Andrews"
   LastChanged "Paul Andrews"
  }
  CustomStringTableItem "{6213697BC46682BF}" {
   Id "AR-WR_Briefing_Intro_3_Title"
   Target_en_us "Factions"
   Modified 1645560374
   Author "Paul Andrews"
   LastChanged "Paul Andrews"
  }
  CustomStringTableItem "{6213697BB25964C7}" {
   Id "AR-WR_Briefing_Intro_4_Desc"
   Target_en_us "When you spawn, you’ll find yourself in one of the towns on the island. First, you’ll want to look around for vehicles nearby. Weapons and equipment can be found in vehicle inventories. You’ll want to make sure you find a capable vehicle to get yourself around the map and transport whatever loot you gather."
   Modified 1645560345
   Author "Paul Andrews"
   LastChanged "Paul Andrews"
  }
  CustomStringTableItem "{6213697BB9F25D32}" {
   Id "AR-WR_Briefing_Intro_4_Title"
   Target_en_us "Gearing up"
   Modified 1645560378
   Author "Paul Andrews"
   LastChanged "Paul Andrews"
  }
  CustomStringTableItem "{6213697BA6AE0A3B}" {
   Id "AR-WR_Briefing_Intro_5_Desc"
   Target_en_us "A random selection of missions are regularly available around the island. They offer valuable rewards, but are usually guarded by a squad of armed NPCs. Rewards range from crates full of weapons to armored vehicles or bases full of supplies."\
   ""\
   "Be careful: locations of missions are always marked on every player’s map, so getting away with the spoils can get competitive."
   Modified 1645560349
   Author "Paul Andrews"
   LastChanged "Paul Andrews"
  }
  CustomStringTableItem "{6213697BABC238A1}" {
   Id "AR-WR_Briefing_Intro_5_Title"
   Target_en_us "Missions"
   Modified 1645560386
   Author "Paul Andrews"
   LastChanged "Paul Andrews"
  }
  CustomStringTableItem "{6213697B8E1A6605}" {
   Id "AR-WR_Briefing_Intro_6_Desc"
   Target_en_us "Base building is currently available in Wasteland using Construction Trucks. Find one, load it up with supplies, then construct a base anywhere in the world."\
   ""\
   "See ‘Free Roam Building’ in the ‘Conflict’ section of the Field Manual for more information on how to build bases."
   Modified 1645560358
   Author "Paul Andrews"
   LastChanged "Paul Andrews"
  }
  CustomStringTableItem "{6213697B929E775C}" {
   Id "AR-WR_Briefing_Intro_6_Title"
   Target_en_us "Base building"
   Modified 1645560392
   Author "Paul Andrews"
   LastChanged "Paul Andrews"
  }
 }
}